/**
 * Catalogue entity matching — the ONE implementation used by release cards,
 * the release modal, tool/model detail pages AND scripts/prerender.ts, so the
 * live SPA and the static HTML can never disagree about what links where.
 *
 * Data source is src/data/entity-index.json (regenerated by
 * scripts/build-entity-index.ts): a slim {name, slug} list of landscape tools
 * that have a detail page (→ /tools/<slug>/) and every LLM-registry version
 * (→ /models/<slug>/). Deliberately NOT the full landscape/registry JSON —
 * this module ships in the main feed bundle.
 *
 * Matching is conservative on purpose (the false-positive trap of free-text
 * entity linking over 800+ names — "Continue", "Cursor", "Jan" are real
 * English words too):
 *   - release matching runs ONLY over the item's title + tags;
 *   - whole-word, ≥3 chars, LONGEST match wins on overlap (so a
 *     "Sentence Transformers" release links sentence-transformers, not the
 *     unrelated transformers page), capped per kind;
 *   - prose cross-matching (tool page ↔ model page) is case-SENSITIVE so the
 *     brand "Cursor" matches but the word "cursor" does not.
 */

import entityIndex from "../data/entity-index.json";
import { learnToolPath } from "../data/learn/schema";
import { modelPath } from "../data/models/schema";

export interface EntityRef {
  name: string;
  slug: string;
}

export interface LinkEntity {
  name: string;
  slug: string;
  /** Namespaced dedup key ("tool:vllm" / "model:gpt-5-5"). */
  key: string;
  /** Site-absolute destination ("/tools/vllm/" / "/models/gpt-5-5/"). */
  href: string;
  kind: "tool" | "model";
}

const INDEX = entityIndex as { tools: EntityRef[]; models: EntityRef[] };

export const TOOL_ENTITIES: EntityRef[] = INDEX.tools;
export const MODEL_ENTITIES: EntityRef[] = INDEX.models;

const isWord = (ch: string | undefined) => ch !== undefined && /[a-z0-9]/i.test(ch);

/**
 * First whole-word occurrence of `needle` in `hay`, or -1. Both args must
 * already share a case convention (callers lowercase for insensitive).
 *
 * Beyond the plain word boundary, a match glued to a VERSION/COMPOUND
 * continuation is rejected: "." or "-" followed by an alphanumeric. Without
 * this, "GPT-5" matches inside "GPT-5.6" and "Qwen3" inside "Qwen3.8" —
 * linking the WRONG version whenever the exact one isn't in the registry
 * (longest-match-wins only helps when the longer name exists). Same on the
 * left, so "Codex" can't match inside "GPT-5.3-Codex".
 */
function wholeWordIndex(hay: string, needle: string, start = 0): number {
  let from = start;
  for (;;) {
    const i = hay.indexOf(needle, from);
    if (i === -1) return -1;
    const before = hay[i - 1];
    const after = hay[i + needle.length];
    const okBefore =
      !isWord(before) &&
      !((before === "." || before === "-") && isWord(hay[i - 2]));
    const okAfter =
      !isWord(after) &&
      !((after === "." || after === "-") && isWord(hay[i + needle.length + 1]));
    if (okBefore && okAfter) return i;
    from = i + 1;
  }
}

interface Match {
  ref: EntityRef;
  kind: "tool" | "model";
  idx: number;
  len: number;
}

function toLink(m: { ref: EntityRef; kind: "tool" | "model" }): LinkEntity {
  return {
    name: m.ref.name,
    slug: m.ref.slug,
    kind: m.kind,
    key: `${m.kind}:${m.ref.slug}`,
    href: m.kind === "tool" ? learnToolPath(m.ref.slug) : modelPath(m.ref.slug),
  };
}

/**
 * Catalogue entities this release is genuinely about: whole-word name matches
 * in its title + tags, longest-first with overlap suppression, capped at 3
 * tools + 3 models, returned in order of first appearance.
 */
export function releaseEntities(item: {
  title: string;
  tags: string[];
}): LinkEntity[] {
  const hay = ` ${item.title} ${item.tags.join(" ")} `.toLowerCase();
  const tagHay = ` ${item.tags.join(" ")} `.toLowerCase();
  const matches: Match[] = [];
  const scan = (refs: EntityRef[], kind: "tool" | "model") => {
    for (const ref of refs) {
      const n = ref.name.toLowerCase();
      if (n.length < 3) continue; // 1–2 char names ("ML") are pure noise
      // Dictionary-shaped names ("Sim", "Evidence", "Continue") are plain
      // English in a headline ("Fake Evidence", "IPO Guidance") — demand a
      // second signal beyond the cased title match: the item tags the name,
      // OR the name OPENS the title (product releases lead with the name —
      // "Goose v1.2 —", "Ray 2.58.0"; coincidental words sit mid-headline).
      if (PLAIN_WORD_RE.test(ref.name)) {
        const idx = wholeWordIndex(item.title, ref.name);
        if (idx === 0 || (idx > 0 && wholeWordIndex(tagHay, n) !== -1))
          matches.push({ ref, kind, idx: idx + 1, len: n.length });
        continue;
      }
      const idx = wholeWordIndex(hay, n);
      if (idx !== -1) matches.push({ ref, kind, idx, len: n.length });
    }
  };
  scan(TOOL_ENTITIES, "tool");
  scan(MODEL_ENTITIES, "model");

  // Longest match wins where ranges overlap ("Sentence Transformers" beats
  // "Transformers"), then keep reading order; cap per kind.
  matches.sort((a, b) => b.len - a.len);
  const accepted: Match[] = [];
  for (const m of matches) {
    const overlaps = accepted.some(
      (a) => m.idx < a.idx + a.len && a.idx < m.idx + m.len,
    );
    if (!overlaps) accepted.push(m);
  }
  accepted.sort((a, b) => a.idx - b.idx);
  const out: LinkEntity[] = [];
  let tools = 0;
  let models = 0;
  for (const m of accepted) {
    if (m.kind === "tool" && tools >= 3) continue;
    if (m.kind === "model" && models >= 3) continue;
    if (m.kind === "tool") tools++;
    else models++;
    out.push(toLink(m));
  }
  return out;
}

/** One piece of a linkified prose string: plain text, or a link segment. */
export type ProseSegment = { text: string; href?: string; key?: string };

/**
 * Split raw prose into segments, linking the FIRST mention of each entity
 * (case-insensitive whole word). `used` is shared by the caller across all
 * prose blocks on a page, enforcing first-mention-only page-wide. Callers
 * pass ONLY entities already matched for this page (releaseEntities /
 * entitiesInText), never the whole index.
 */
export function linkifyProse(
  text: string,
  entities: LinkEntity[],
  used: Set<string>,
): ProseSegment[] {
  if (!text) return [];
  const hay = text.toLowerCase();
  let best: { idx: number; len: number; e: LinkEntity } | null = null;
  for (const e of entities) {
    if (used.has(e.key) || e.name.length < 3) continue;
    const idx = wholeWordIndex(hay, e.name.toLowerCase());
    if (idx !== -1 && (best === null || idx < best.idx)) {
      best = { idx, len: e.name.length, e };
    }
  }
  if (!best) return [{ text }];
  used.add(best.e.key);
  const segments: ProseSegment[] = [];
  if (best.idx > 0) segments.push({ text: text.slice(0, best.idx) });
  segments.push({
    text: text.slice(best.idx, best.idx + best.len),
    href: best.e.href,
    key: best.e.key,
  });
  return segments.concat(
    linkifyProse(text.slice(best.idx + best.len), entities, used),
  );
}

/**
 * Entities of `kind` NAMED in a page's own prose — used for tool ↔ LLM
 * cross-links (a tool page's "Related models", a model page's "Works with").
 * Case-SENSITIVE whole-word match: brand names are capitalized mid-sentence
 * ("Cursor", "Jan"), the identical common words are not — that one bit of
 * signal removes almost all false positives in free prose.
 */
/** An ordinary single capitalized word ("Continue", "Accelerate", "Jan") —
 *  the shape most likely to be plain English rather than a brand mention. */
const PLAIN_WORD_RE = /^[A-Z][a-z]+$/;

/** True when the match at `idx` opens a sentence/line — where ANY word is
 *  capitalized, so capitalization carries no brand signal. */
function sentenceInitial(text: string, idx: number): boolean {
  let i = idx - 1;
  while (i >= 0 && /[\s"'“”‘’([]/.test(text[i])) i--;
  return i < 0 || /[.!?:;\n]/.test(text[i]);
}

export function entitiesInText(
  text: string,
  kind: "tool" | "model",
  excludeSlug?: string,
  cap = 4,
): LinkEntity[] {
  const refs = kind === "tool" ? TOOL_ENTITIES : MODEL_ENTITIES;
  const matches: Match[] = [];
  for (const ref of refs) {
    if (ref.slug === excludeSlug || ref.name.length < 3) continue;
    let idx = wholeWordIndex(text, ref.name);
    // For dictionary-shaped names, require an occurrence that is NOT
    // sentence-initial — "Continue reading…" must not link the Continue
    // tool, while "…editors like Continue" still does.
    if (PLAIN_WORD_RE.test(ref.name)) {
      while (idx !== -1 && sentenceInitial(text, idx)) {
        idx = wholeWordIndex(text, ref.name, idx + 1);
      }
    }
    if (idx !== -1) matches.push({ ref, kind, idx, len: ref.name.length });
  }
  matches.sort((a, b) => b.len - a.len);
  const accepted: Match[] = [];
  for (const m of matches) {
    const overlaps = accepted.some(
      (a) => m.idx < a.idx + a.len && a.idx < m.idx + m.len,
    );
    // one link per slug even if named twice
    const dup = accepted.some((a) => a.ref.slug === m.ref.slug);
    if (!overlaps && !dup) accepted.push(m);
  }
  accepted.sort((a, b) => a.idx - b.idx);
  return accepted.slice(0, cap).map(toLink);
}

/**
 * One row in an entity's "In the news" list. The full maps live in the
 * GENERATED src/data/learn/tool-news.json and src/data/models/model-news.json
 * (built by scripts/build-entity-index.ts by inverting releaseEntities over
 * the feed) — slim on purpose, so the lazy learn/models chunks never import
 * the multi-MB releases.json.
 */
export interface EntityNewsRef {
  id: string;
  /** Public release date (YYYY-MM-DD) — the list is newest-first by this. */
  date: string;
  title: string;
  importance: string;
}
